server:
  port: 8007
  ssl:
    keyStorePassword: '!Keypass1'
    keyStoreType: PKCS12
    keyStore: classpath:keystore.p12
    keyAlias: localhost
#    keyStore: classpath:rootKey.key

#
#facebook:
#  client:
#    cliendId: 1124212834409853
security:
  oauth2:
    client:
      clientId: 1124212834409853
      clientSecret: 95da02df0862ede4094e48ccde7dad27
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me?fields=id,name,email,picture

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/
  instance:
    hostname: localhost