server:
  port: 8007
  ssl:
    keyStorePassword: '!Keypass1'
    keyStoreType: PKCS12
    keyStore: classpath:keystore.p12
    keyAlias: localhost
#    keyStore: classpath:rootKey.key

#
#facebook:
#  client:
#    cliendId: 1124212834409853
facebook:
  client:
    clientId: 1124212834409853
    clientSecret: 95da02df0862ede4094e48ccde7dad27
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id,name,email,picture

vk:
  client:
    clientId: 6787600
    clientSecret: uVUKPPl64L4I9PvqesLZ
    accessTokenUri: https://oauth.vk.com/access_token
    userAuthorizationUri: https://oauth.vk.com/authorize
    tokenName: code
    authenticationScheme: query
    clientAuthenticationScheme: form
    grant-type: authorization_code
    redirectUri: https://localhost:8007/login/vk
    scope: email
  resource:
    userInfoUri: https://api.vk.com/method/users.get
  openApi:
    version: 5.92

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8002/eureka/
#  instance:
#    hostname: localhost
spring:
  mvc:
    view:
      suffix: .html
