eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/
  instance:
    hostname: localhost

server:
  port: 8005

management:
  endpoints:
    web:
      exposure:
        include: *
